# Generated by Django 5.0.3 on 2024-03-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_nome', models.CharField(default='', max_length=70)),
                ('mod_descri', models.CharField(default='', max_length=200)),
                ('mod_qtd_time', models.IntegerField()),
                ('publicado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'modalidades',
            },
        ),
    ]
