# Generated by Django 5.0.3 on 2024-06-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el_camp_nome', models.CharField(default='', max_length=100)),
                ('el_equipe_nome', models.CharField(default='', max_length=100)),
                ('el_at_nome', models.CharField(default='', max_length=100)),
                ('el_at_dnasc', models.DateField()),
                ('el_at_nota', models.IntegerField()),
            ],
            options={
                'db_table': 'elencos',
            },
        ),
    ]
