# Generated by Django 5.0.3 on 2024-04-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipe_nome', models.CharField(default='', max_length=100)),
                ('publicado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'equipes',
            },
        ),
    ]
